export interface NavItem {
  title: string;
  href: string;
}

export interface Service {
  icon: string;
  title: string;
  description: string;
}

export interface Testimonial {
  name: string;
  company: string;
  image: string;
  quote: string;
  rating: number;
}

export interface Project {
  title: string;
  description: string;
  image: string;
  category: string;
  link: string;
}

export interface BlogPost {
  title: string;
  excerpt: string;
  image: string;
  date: string;
  author: string;
  link: string;
}

// ---------------------------------------------------------------------------
// Supabase-backed blog types
// ---------------------------------------------------------------------------

/**
 * Mirrors the `blog_posts` Postgres table in Supabase.
 *
 * - `id`         → UUID primary key (auto-generated by Supabase).
 * - `content`    → Raw HTML string, compatible with existing blog UI rendering.
 * - `tags`       → Stored as a Postgres `text[]` array column.
 * - `created_at` → Managed by Supabase (`default now()`).
 * - `featured`   → Nullable; defaults to false in the DB.
 *
 * When fetching rows, map `DbBlogPost` → the component-level `BlogPost`
 * shape if the consuming component still expects the legacy interface.
 */
export interface DbBlogPost {
  id: string;            // UUID
  slug: string;
  title: string;
  excerpt: string;
  content: string;       // HTML string for existing UI rendering
  image: string;
  category: string;
  author: string;
  date: string;          // Publication date (ISO string or display format)
  read_time: string;
  tags: string[];
  featured: boolean;
  is_pinned: boolean;   // New: dedicated flag for homepage pinning
  target_sites?: string[]; // Target websites e.g. ['yellowbagney', 'yellowtools']
  canonical_site?: string;
  created_at: string;    // ISO 8601 timestamp from Supabase
  updated_at?: string;   // Optional: populated if the row has been edited
}